//You are given two strings s and t.
//
// String t is generated by random shuffling string s and then add one more
//letter at a random position.
//
// Return the letter that was added to t.
//
//
// Example 1:
//
//
//Input: s = "abcd", t = "abcde"
//Output: "e"
//Explanation: 'e' is the letter that was added.
//
//
// Example 2:
//
//
//Input: s = "", t = "y"
//Output: "y"
//
//
//
// Constraints:
//
//
// 0 <= s.length <= 1000
// t.length == s.length + 1
// s and t consist of lowercase English letters.
//
//
// Related Topics Hash Table String Bit Manipulation Sorting 👍 4576 👎 449
#include <string>
using namespace std;

//leetcode submit region begin(Prohibit modification and deletion)
class Solution
{
public:
    [[maybe_unused]] static char findTheDifference(const string &s, const string &t)
    {
        int num = 0;
        for (char i: s) {

            num = num ^ ((int) i);
        }
        for (char i: t) {

            num = num ^ ((int) i);
        }

        return (char) num;
    }
};
//leetcode submit region end(Prohibit modification and deletion)
